### PR TITLE
Fix "copy curl command" on unsecure context

### LINKED ISSUE #91: Copy cURL command not working
As stated in #89 , looks like there's an issue on some browser:

Image

Looks like the clipboard feature is only available on secure context (= HTTPS), see: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard .

We should check if the clipboard feature is available and if not, propose something else to show the command to the user.

@decryptedchaos you were using vivaldi? On HTTP?

### PR DESCRIPTION
**Pull request by YuukanOO**
Replaced with a "show curl command".

Extend the `Console` component to include a "copy" button if the `clipboard` is available and a "select all" button. 

image

### CODE REVIEW

File: cmd/serve/front/src/components/button-base.svelte [hunk 1]
```diff
@@ -13,6 +12,9 @@
 	export let variant: 'primary' | 'outlined' | 'danger' = 'primary';
 	export let loading: boolean = false;
 
+	export let ariaExpanded = false;
```
Comment (YuukanOO) [inline cmd/serve/front/src/components/button-base.svelte:15]: For each cross-cutting concerns like this, we better expose a `use` property on components, something inspired by https://github.com/hperrin/svelte-material-ui/blob/9effccdf972b19a901a9b512981844e71182596f/packages/button/src/Button.svelte#L80
